[build]
  # Build correct pour votre structure
  command = "npm install && npx tsc && mkdir -p dist && cp -r public/* dist/"
  
  # Dossier de publication
  publish = "dist"

# Variables d'environnement
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# Configuration pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour les SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les fichiers TypeScript compilés
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"