[build]
  # Commande de build simplifiée
  command = "npm install && npm run build"
  
  # Dossier de publication
  publish = "dist"

# Variables d'environnement
[build.environment]
  # Désactive le plugin Next.js
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  
  # Version Node.js
  NODE_VERSION = "18"
  
  # Variables pour le build
  NODE_ENV = "production"

# Configuration pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour les SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les fichiers TypeScript compilés
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"