[build]
  # Build avec debug pour voir ce qui se passe
  command = "npm install && npx tsc && ls -la dist/ && cp -r public/* dist/ && ls -la dist/"
  
  # Dossier de publication
  publish = "dist"

# Variables d'environnement
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# Headers pour les fichiers JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Headers pour les fichiers CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Headers pour les fichiers HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# Configuration pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour les SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les fichiers TypeScript compilés
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"