[build]
  # Build qui place les fichiers au bon endroit
  command = "npm install && npx tsc && cp -r public/* dist/ && cp dist/index.js dist/main.js || true"
  
  # Dossier de publication
  publish = "dist"

# Variables d'environnement
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

# Headers pour servir les JS en tant que modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Configuration pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour les SPA (Single Page Applications)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les fichiers TypeScript compilés
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"